version: '3.8'
services:
  secure-share:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./tls:/tls
    environment:
      REDIS_ADDR: "redis:6379"
      BASE_URL: "localhost:8080"
      STORE_BACKEND: "redis"
      DEBUG_MODE: "false"
      TLS_ENABLED: "true"
      CERT_FILE: "/tls/server.crt"
      KEY_FILE: "/tls/server.key"
      # TITLE: "The best team"
      # SUBTITLE: "Make the shareholders happy and keep the money flowing."
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
