apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secureshare.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "secureshare.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "secureshare.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "secureshare.fullname" . }}
          {{- if .Values.redis.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.redisAuth.secretName }}
                  key: {{ .Values.config.redisAuth.secretKey }}
          {{- end }}
