apiVersion: v1
kind: Service
metadata:
  name: {{ include "secureshare.fullname" . }}
  labels:
    {{- include "secureshare.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "secureshare.selectorLabels" . | nindent 4 }}
